In [2]:
import numpy as np

In [3]:
a = np.arange(10)
print(a)

b = np.arange(2,10,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [4]:
z = np.zeros(2)
print(z)

o = np.ones(2)
print(o)

[0. 0.]
[1. 1.]


In [5]:
c = np.reshape(b, (2,2))
print(c)

[[2 4]
 [6 8]]


In [6]:
b.shape

(4,)

In [7]:
c.shape

(2, 2)

In [8]:
c1 = np.reshape(b,(4,1))
print(c1)

[[2]
 [4]
 [6]
 [8]]


In [9]:
c1.shape

(4, 1)

In [10]:
v1 = np.arange(1,9,2)
print(v1)
v2 = np.arange(2,10,2)
print(v2)

[1 3 5 7]
[2 4 6 8]


In [11]:
v1.shape


(4,)

In [12]:
v2.shape

(4,)

In [13]:
v1 = np.reshape(v1, (2,2))
print(v1)

[[1 3]
 [5 7]]


In [14]:
v1.shape

(2, 2)

In [15]:
v2 = np.reshape(v2,(2,2))
print(v2)
v2.shape

[[2 4]
 [6 8]]


(2, 2)

In [16]:
v = np.vstack((v1,v2))
print(v)

[[1 3]
 [5 7]
 [2 4]
 [6 8]]


In [17]:
v = np.stack((v1,v2))
print(v)

[[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]


In [18]:
v = np.hstack((v1,v2))
print(v)

[[1 3 2 4]
 [5 7 6 8]]


In [19]:
print(v.max())
print(v.min())

8
1


# Pandas Documentations

In [20]:
import pandas as pd

In [21]:
s = pd.Series([1,2,3,np.nan,5])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64

In [22]:
dates = pd.date_range('20200101',periods=6)
print(dates)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')


In [23]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

In [24]:
df

A         B         C         D
2020-01-01 -1.248500  0.040982 -0.364569 -0.323592
2020-01-02  0.533685  0.901927  1.053689 -0.112199
2020-01-03  0.447770 -2.089684 -2.274698  2.745026
2020-01-04 -1.378702  0.149162  1.385743 -2.154352
2020-01-05 -0.146125  0.315261 -0.910548  0.358800
2020-01-06 -0.261444  1.378250 -0.097307 -0.290072

In [25]:
df2 = pd.DataFrame({
    'A': 1,
    'B':pd.Timestamp('20200101'),
    'C':pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3]*4,dtype='int32'),
    'E':pd.Categorical(['test','train','test','train']),
    'F':'foo'
})

In [26]:
df2

A          B    C  D      E    F
0  1 2020-01-01  1.0  3   test  foo
1  1 2020-01-01  1.0  3  train  foo
2  1 2020-01-01  1.0  3   test  foo
3  1 2020-01-01  1.0  3  train  foo

In [27]:
df2.dtypes

A             int64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [30]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.342219  0.115983 -0.201282  0.037268
std    0.816322  1.193518  1.336651  1.581028
min   -1.378702 -2.089684 -2.274698 -2.154352
25%   -1.001736  0.068027 -0.774053 -0.315212
50%   -0.203785  0.232211 -0.230938 -0.201136
75%    0.299296  0.755261  0.765940  0.241050
max    0.533685  1.378250  1.385743  2.745026